
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int BOOLLIT = 50;
  public static final int POW = 31;
  public static final int LBRACKET = 24;
  public static final int CHAR = 48;
  public static final int READINT = 11;
  public static final int CASE = 9;
  public static final int LPAREN = 14;
  public static final int SEMI = 16;
  public static final int INT = 43;
  public static final int PRINTLN = 13;
  public static final int MINUS = 27;
  public static final int TILDE = 38;
  public static final int BAR = 37;
  public static final int RPAREN = 15;
  public static final int BCOMS = 40;
  public static final int NOT = 35;
  public static final int AND = 33;
  public static final int OR = 34;
  public static final int COMMA = 23;
  public static final int CALL = 3;
  public static final int DIV = 29;
  public static final int PLUS = 26;
  public static final int BCOME = 41;
  public static final int ASSIGN = 32;
  public static final int IF = 6;
  public static final int EOF = 0;
  public static final int AMP = 36;
  public static final int EQUAL = 46;
  public static final int RBRACKET = 25;
  public static final int DQUOTE = 20;
  public static final int error = 1;
  public static final int MUL = 28;
  public static final int MOD = 30;
  public static final int COMPARISON = 45;
  public static final int COLON = 17;
  public static final int LBRACE = 21;
  public static final int ELSE = 8;
  public static final int NL = 42;
  public static final int READ = 10;
  public static final int FLOAT = 47;
  public static final int LET = 4;
  public static final int THEN = 7;
  public static final int RBRACE = 22;
  public static final int LCOM = 39;
  public static final int STRING = 49;
  public static final int PROC = 2;
  public static final int DEF = 5;
  public static final int ELIST = 19;
  public static final int AT = 18;
  public static final int VAR = 44;
  public static final int PRINT = 12;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "PROC",
  "CALL",
  "LET",
  "DEF",
  "IF",
  "THEN",
  "ELSE",
  "CASE",
  "READ",
  "READINT",
  "PRINT",
  "PRINTLN",
  "LPAREN",
  "RPAREN",
  "SEMI",
  "COLON",
  "AT",
  "ELIST",
  "DQUOTE",
  "LBRACE",
  "RBRACE",
  "COMMA",
  "LBRACKET",
  "RBRACKET",
  "PLUS",
  "MINUS",
  "MUL",
  "DIV",
  "MOD",
  "POW",
  "ASSIGN",
  "AND",
  "OR",
  "NOT",
  "AMP",
  "BAR",
  "TILDE",
  "LCOM",
  "BCOMS",
  "BCOME",
  "NL",
  "INT",
  "VAR",
  "COMPARISON",
  "EQUAL",
  "FLOAT",
  "CHAR",
  "STRING",
  "BOOLLIT"
  };
}

