
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int BOOLLIT = 68;
  public static final int POW = 39;
  public static final int LBRACKET = 31;
  public static final int CHAR = 66;
  public static final int READINT = 11;
  public static final int CAR = 56;
  public static final int CASE = 9;
  public static final int CDR = 57;
  public static final int LPAREN = 21;
  public static final int SEMI = 23;
  public static final int CONTINUE = 20;
  public static final int REPEAT = 17;
  public static final int INT = 61;
  public static final int PRINTLN = 13;
  public static final int MINUS = 35;
  public static final int FOR = 15;
  public static final int TILDE = 47;
  public static final int BAR = 46;
  public static final int RPAREN = 22;
  public static final int BCOMS = 49;
  public static final int NOT = 43;
  public static final int AND = 41;
  public static final int IN = 44;
  public static final int OR = 42;
  public static final int COMMA = 30;
  public static final int CALL = 3;
  public static final int DIV = 37;
  public static final int UNTIL = 18;
  public static final int PLUS = 34;
  public static final int BCOME = 50;
  public static final int ASSIGN = 40;
  public static final int IF = 6;
  public static final int DOT = 33;
  public static final int EOF = 0;
  public static final int AMP = 45;
  public static final int EQUAL = 64;
  public static final int RBRACKET = 32;
  public static final int DQUOTE = 27;
  public static final int SIZE = 58;
  public static final int error = 1;
  public static final int MUL = 36;
  public static final int MOD = 38;
  public static final int ISPAIR = 52;
  public static final int BREAK = 19;
  public static final int PAIR = 53;
  public static final int COMPARISON = 63;
  public static final int COLON = 24;
  public static final int LBRACE = 28;
  public static final int ELSE = 8;
  public static final int NL = 51;
  public static final int READ = 10;
  public static final int ISEQV = 54;
  public static final int WHILE = 16;
  public static final int LIST = 59;
  public static final int SUBSTR = 60;
  public static final int FLOAT = 65;
  public static final int LET = 4;
  public static final int THEN = 7;
  public static final int RBRACE = 29;
  public static final int LCOM = 48;
  public static final int STRING = 67;
  public static final int PROC = 2;
  public static final int DEF = 5;
  public static final int ELIST = 26;
  public static final int AT = 25;
  public static final int VAR = 62;
  public static final int PRINT = 12;
  public static final int DO = 14;
  public static final int ISEQ = 55;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "PROC",
  "CALL",
  "LET",
  "DEF",
  "IF",
  "THEN",
  "ELSE",
  "CASE",
  "READ",
  "READINT",
  "PRINT",
  "PRINTLN",
  "DO",
  "FOR",
  "WHILE",
  "REPEAT",
  "UNTIL",
  "BREAK",
  "CONTINUE",
  "LPAREN",
  "RPAREN",
  "SEMI",
  "COLON",
  "AT",
  "ELIST",
  "DQUOTE",
  "LBRACE",
  "RBRACE",
  "COMMA",
  "LBRACKET",
  "RBRACKET",
  "DOT",
  "PLUS",
  "MINUS",
  "MUL",
  "DIV",
  "MOD",
  "POW",
  "ASSIGN",
  "AND",
  "OR",
  "NOT",
  "IN",
  "AMP",
  "BAR",
  "TILDE",
  "LCOM",
  "BCOMS",
  "BCOME",
  "NL",
  "ISPAIR",
  "PAIR",
  "ISEQV",
  "ISEQ",
  "CAR",
  "CDR",
  "SIZE",
  "LIST",
  "SUBSTR",
  "INT",
  "VAR",
  "COMPARISON",
  "EQUAL",
  "FLOAT",
  "CHAR",
  "STRING",
  "BOOLLIT"
  };
}

